[2024-06-10T09:09:46.648+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-10T09:09:46.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_airflow_postgres_connection_dag_2.test_airflow_postgres_connection_task manual__2024-06-10T09:09:45.971617+00:00 [queued]>
[2024-06-10T09:09:46.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_airflow_postgres_connection_dag_2.test_airflow_postgres_connection_task manual__2024-06-10T09:09:45.971617+00:00 [queued]>
[2024-06-10T09:09:46.682+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-10T09:09:46.689+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_airflow_postgres_connection_task> on 2024-06-10 09:09:45.971617+00:00
[2024-06-10T09:09:46.693+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_***_postgres_connection_dag_2', 'test_***_postgres_connection_task', 'manual__2024-06-10T09:09:45.971617+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_testconnection.py', '--cfg-path', '/tmp/tmpicy_hf1m']
[2024-06-10T09:09:46.696+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=707) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-10T09:09:46.697+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask test_***_postgres_connection_task
[2024-06-10T09:09:46.697+0000] {standard_task_runner.py:63} INFO - Started process 708 to run task
[2024-06-10T09:09:46.729+0000] {task_command.py:426} INFO - Running <TaskInstance: test_airflow_postgres_connection_dag_2.test_airflow_postgres_connection_task manual__2024-06-10T09:09:45.971617+00:00 [running]> on host 5f414d64f7b6
[2024-06-10T09:09:46.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_***_postgres_connection_dag_2' AIRFLOW_CTX_TASK_ID='test_***_postgres_connection_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-10T09:09:45.971617+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-10T09:09:45.971617+00:00'
[2024-06-10T09:09:46.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-10T09:09:46.789+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-10T09:09:46.790+0000] {logging_mixin.py:188} INFO - Koneksi gagal: connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-06-10T09:09:46.791+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-10T09:09:46.791+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-10T09:09:46.795+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_***_postgres_connection_dag_2, task_id=test_***_postgres_connection_task, run_id=manual__2024-06-10T09:09:45.971617+00:00, execution_date=20240610T090945, start_date=20240610T090946, end_date=20240610T090946
[2024-06-10T09:09:46.841+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-10T09:09:46.849+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-10T09:09:46.850+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
