[2024-06-11T08:31:45.748+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T08:31:45.763+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_ingest_cybertrack_nmb_v_merchant_transaction.load_to_postgresql manual__2024-06-11T08:31:44.259342+00:00 [queued]>
[2024-06-11T08:31:45.766+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_ingest_cybertrack_nmb_v_merchant_transaction.load_to_postgresql manual__2024-06-11T08:31:44.259342+00:00 [queued]>
[2024-06-11T08:31:45.767+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T08:31:45.772+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgresql> on 2024-06-11 08:31:44.259342+00:00
[2024-06-11T08:31:45.775+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7160) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-11T08:31:45.776+0000] {standard_task_runner.py:63} INFO - Started process 7161 to run task
[2024-06-11T08:31:45.775+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_ingest_cybertrack_nmb_v_merchant_transaction', 'load_to_postgresql', 'manual__2024-06-11T08:31:44.259342+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/dag_nmb.py', '--cfg-path', '/tmp/tmpipws01lt']
[2024-06-11T08:31:45.777+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask load_to_postgresql
[2024-06-11T08:31:45.803+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_ingest_cybertrack_nmb_v_merchant_transaction.load_to_postgresql manual__2024-06-11T08:31:44.259342+00:00 [running]> on host 2e5c63130483
[2024-06-11T08:31:45.840+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_ingest_cybertrack_nmb_v_merchant_transaction' AIRFLOW_CTX_TASK_ID='load_to_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T08:31:44.259342+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T08:31:44.259342+00:00'
[2024-06-11T08:31:45.841+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T08:31:45.876+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-06-11T08:31:45.880+0000] {sql.py:470} INFO - Running statement: 
    INSERT INTO raw_data.cybertrack_nmb_v_merchant_transaction (
        "Id",
        "MPANID",
        "NMID",
        "MerchantID",
        "MerchantName",
        "MerchantPhone",
        "MerchantEmail",
        "MerchantType",
        "MerchantStatus",
        "MerchantCurrency",
        "RegisterLongitude",
        "RegisterLatitude",
        "RegisterCountry",
        "TransactionID",
        "TransactionTimestamp",
        "TransactionDatetime",
        "TransactionType",
        "TransactionChannel",
        "TransactionAmount",
        "IssuerName",
        "TransactionStatus",
        "TransactionMessage",
        "CPANID",
        "StoreID",
        "IssuerID",
        "MID",
        "timegetdata"
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    , parameters: [1, '936005030000080783', 'ID2024316526696', '01234326092943', 'a1518a34170902b1a77f85cd32ba8d53', '51e0de12ba323db8191b75b8e66e9c1a', '5bda3dd54506b7b9d47a3266e16ee5a9', 'CORPORATE', 'ACTIVE', '360', '106737', '-6161188', 'ID', 745256135, datetime.datetime(2024, 10, 6, 0, 0), datetime.datetime(2024, 10, 6, 0, 0), 'PAY', 'NMB', 55000, 'Mandiri Pay', 'SUCCESS', '{"msgType":"0200","trxPAN":"9360050300000807836","trxCode":"261000","trxAmount":"000005500000","transmissionDateTime":"0609165959","msgSTAN":"875340","trxTime":"235939","trxDate":"0609","settlementDate":"0611","captureDate":"0610","merchantType":"5499","posEntryMode":"011","trxFeeAmount":"C00000000","acquirerID":"93600503","forwardingID":"360002","retrievalReferenceNumber":"406491352172","approvalCode":"014531","responseCode":"","terminalID":"A01             ","merchantID":"01234326092943 ","merchantNameLocation":"darthvader08             JAKARTA BARATID","additionalDataPrivate":"PI04Q001CD18SURYA ADIB PRATAMAMC03UME","trxCurrencyCode":"360","issuerID":"93600008","fromAccount":"9360000812145262165","invoiceNumber":"","channelId":null,"channelSwitching":"arta_jasa","additionalDataNational":"6105121906257011406090800768883062001I2R7RNRY9WG8ACM8EC0703A010804POSP"}', '', 1578286, '93600008', '01234326092943', '2024-06-11 15:31:44']
[2024-06-11T08:31:45.880+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T08:31:45.881+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_nmb.py", line 74, in load_to_postgresql
    pg_hook.run(insert_query, parameters=record)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 473, in _run_command
    cur.execute(sql_statement, parameters)
IndexError: list index out of range
[2024-06-11T08:31:45.886+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_ingest_cybertrack_nmb_v_merchant_transaction, task_id=load_to_postgresql, run_id=manual__2024-06-11T08:31:44.259342+00:00, execution_date=20240611T083144, start_date=20240611T083145, end_date=20240611T083145
[2024-06-11T08:31:45.891+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 116 for task load_to_postgresql (list index out of range; 7161)
[2024-06-11T08:31:45.919+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T08:31:45.929+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T08:31:45.931+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
